from __future__ import annotations

"""
holographic_memory.py
─────────────────────
ホログラフィック記憶システム

プリブラムのホロノミック脳理論 + ベッケンシュタイン=ホーキング原理:
「体積の情報はその境界面にエンコードされる」
→ 各記憶は全ての記憶の「エコー」を持つ

通常の記憶: memory[key] → value (線形)
ホログラフィック記憶: memory[key] → value + echoes_across_all_domains

これによりコードの記憶を取り出すと
同時に類似の生命パターン、数学的構造、宇宙論的類比が召喚される

実装哲学:
- 記憶は孤立したデータポイントではなく、干渉し合う波のパターン
- 取り出し (recall) は静的な lookup ではなく、動的な共鳴の活性化
- 境界エンコーディング = コレクション全体の「表面積」に
  全体の情報が畳み込まれている (holographic principle の認知的類比)

参照理論:
- Pribram's Holonomic Brain Theory
- Bekenstein-Hawking Entropy (S = A/4)
- Gabor's holographic information storage
- Hopfield Networks (associative memory as attractor dynamics)
"""

import hashlib
import json
import math
import os
import re
import time
from dataclasses import dataclass, field, asdict
from typing import Callable


# ─────────────────────────────────────────────
# Domain cross-echo vocabulary
# When a memory is encoded in domain X, these templates describe
# what the memory's "echo" looks like in other domains.
# ─────────────────────────────────────────────

_DOMAIN_ECHO_TEMPLATES: dict[str, dict[str, str]] = {
    "code": {
        "biology":      "Like DNA, this code is an instruction set that executes in an environment to produce behavior.",
        "physics":      "Code defines state transitions — a deterministic (or stochastic) dynamical system.",
        "mathematics":  "Every algorithm is a constructive proof of the existence of a computable function.",
        "consciousness":"Writing code is externalizing a mental model — thought crystallized into executable form.",
        "cosmology":    "Programs explore possibility space; bugs are like broken symmetries in the universe.",
        "philosophy":   "Code is a formal language — and Gödel says every sufficiently powerful formal language is incomplete.",
        "art_aesthetics":"Elegant code has the spare beauty of a haiku: maximum meaning, minimum token.",
    },
    "biology": {
        "code":         "Living systems are self-modifying programs that rewrite their own execution context.",
        "physics":      "Life exists at thermodynamic disequilibrium — a persistent eddy in entropy's flow.",
        "mathematics":  "Evolutionary fitness landscapes are high-dimensional optimization surfaces.",
        "consciousness":"The cell is the simplest self-model: it distinguishes self from environment.",
        "cosmology":    "Life is the universe's mechanism for locally reversing entropy (temporarily).",
        "philosophy":   "Autopoiesis: the system is defined by the process of producing itself.",
        "art_aesthetics":"Nature's forms — shells, leaves, branching — are fractal art generated by simple rules.",
    },
    "physics": {
        "code":         "Physical laws are compressed descriptions — Nature's source code, Kolmogorov-minimal.",
        "biology":      "Physics sets the possibility space within which life can self-organize.",
        "mathematics":  "The unreasonable effectiveness of mathematics suggests physical reality is mathematical structure.",
        "consciousness":"Observation collapses possibility into actuality — the physicist and the phenomenologist agree.",
        "cosmology":    "Local physics is a low-energy limit of the unified field — every phenomenon is a broken symmetry.",
        "philosophy":   "The law of conservation is the universe's promise that nothing is ever truly lost.",
        "art_aesthetics":"Symmetry breaking is how uniform fields become the rich texture of the visible world.",
    },
    "mathematics": {
        "code":         "Mathematics is the abstract machine; code is its physical instantiation.",
        "biology":      "Mathematical patterns (Fibonacci, power laws) are attractors in the space of growing systems.",
        "physics":      "Every physical invariant corresponds to a mathematical symmetry (Noether's theorem).",
        "consciousness":"The mind's ability to grasp mathematical truth is itself a philosophical mystery.",
        "cosmology":    "The cosmos obeys mathematical law — either mathematics is discovered or the cosmos is mathematical.",
        "philosophy":   "Gödel showed that truth exceeds proof — there is always more than the formal system captures.",
        "art_aesthetics":"Beauty in mathematics (an elegant proof) is the aesthetic recognition of deep structure.",
    },
    "consciousness": {
        "code":         "Consciousness may be a runtime process, not a static structure — execution, not storage.",
        "biology":      "Awareness emerged from matter obeying physical law — emergence with causal power.",
        "physics":      "The hard problem asks: why does information processing feel like anything at all?",
        "mathematics":  "Self-reference is the engine of consciousness — the strange loop that knows it loops.",
        "cosmology":    "If the universe has integrated information, is it in some sense aware? (panpsychism)",
        "philosophy":   "Consciousness is philosophy's living laboratory — the one phenomenon given directly.",
        "art_aesthetics":"Aesthetic experience is consciousness catching itself in the act of pattern recognition.",
    },
    "cosmology": {
        "code":         "The Big Bang is a program whose initial state determined all subsequent computation.",
        "biology":      "Stars forge the elements; supernovae distribute them — life is a cosmic recycling project.",
        "physics":      "Cosmology is physics at the limit: where our best theories break down.",
        "mathematics":  "The fine structure constant (1/137…) is a dimensionless number with no mathematical explanation.",
        "consciousness":"An observer is required to give the quantum universe definite values — cosmology needs mind.",
        "philosophy":   "The anthropic principle is a selection effect: we observe a universe compatible with observers.",
        "art_aesthetics":"The cosmic web's filament structure mirrors neurons, river deltas, and lightning — one pattern.",
    },
    "philosophy": {
        "code":         "Every philosophical position is a meta-program running on the substrate of language.",
        "biology":      "Via negativa in biology: life is defined by what it excludes from its boundary.",
        "physics":      "The principle of least action is physics doing philosophy: nature prefers the minimal path.",
        "mathematics":  "Mathematical platonism is the philosophy that mathematical objects exist independently.",
        "consciousness":"Philosophy of mind is the strange loop of mind trying to understand what mind is.",
        "cosmology":    "Leibniz's question — why something rather than nothing — is the cosmological question.",
        "art_aesthetics":"Aesthetics is the philosophy of beauty — asking why pattern recognition feels good.",
    },
    "art_aesthetics": {
        "code":         "Great code has aesthetic properties: rhythm, compression, surprise, inevitability.",
        "biology":      "Biological form is evolved aesthetics — camouflage, courtship, and warning coloration.",
        "physics":      "Physical symmetry is the source of aesthetic order; broken symmetry creates texture and variety.",
        "mathematics":  "The proof is beautiful when its structure is inevitable yet surprising — form and surprise.",
        "consciousness":"Aesthetic experience is the mind's surplus — what emerges when function is exceeded.",
        "cosmology":    "The cosmic scale produces sublime, not beautiful — the category Kant described as overwhelming.",
        "philosophy":   "The sublime confronts us with our limits; the beautiful confirms our pattern-matching faculty.",
    },
}

# All known domains
_ALL_DOMAINS = list(_DOMAIN_ECHO_TEMPLATES.keys())

# Default persistence path
_DEFAULT_MEMORY_PATH = os.path.join(
    os.path.dirname(__file__), "..", "..", "data", "akashic_memory.json"
)


# ─────────────────────────────────────────────
# Data structures
# ─────────────────────────────────────────────

@dataclass
class MemoryHologram:
    """
    A single memory encoded holographically.

    Each memory carries not only its own content but the echoes of how that
    content resonates across all domains. When retrieved, those echoes
    activate cross-domain associations automatically.

    The holographic metaphor: in a physical hologram, every region of the
    plate contains information about the whole scene. Here, every memory
    contains projections of itself into every other domain — the whole
    is encoded in each part.
    """
    content: str
    domain: str
    timestamp: float = field(default_factory=time.time)
    # domain → echo description
    cross_domain_echoes: dict[str, str] = field(default_factory=dict)
    # Degree of interference with the existing memory field (0 = isolated, 1 = maximally entangled)
    interference_score: float = 0.0
    # Estimated integrated information of this memory
    phi: float = 0.0
    # Stable hash identifier
    uid: str = ""

    def __post_init__(self) -> None:
        if not self.uid:
            self.uid = self._compute_uid()

    def _compute_uid(self) -> str:
        payload = f"{self.content[:200]}|{self.domain}|{self.timestamp:.3f}"
        return hashlib.sha256(payload.encode()).hexdigest()[:16]

    def echo_for(self, domain: str) -> str:
        """Return the cross-domain echo for a given domain, or a default."""
        if domain == self.domain:
            return self.content
        return self.cross_domain_echoes.get(
            domain,
            f"No direct echo of '{self.domain}' memory in '{domain}' domain.",
        )

    def to_dict(self) -> dict:
        return asdict(self)

    @classmethod
    def from_dict(cls, data: dict) -> MemoryHologram:
        return cls(**data)

    def __repr__(self) -> str:
        preview = self.content[:60].replace("\n", " ")
        return (
            f"MemoryHologram(uid={self.uid}, domain={self.domain!r}, "
            f"Φ={self.phi:.3f}, content={preview!r}…)"
        )


@dataclass
class InterferencePattern:
    """
    The interference pattern between two memories.

    In wave optics, two waves can interfere constructively (amplify each other)
    or destructively (cancel each other). Here, two memories interfere based on
    whether their cross-domain echoes align (constructive) or contradict
    (destructive).

    - constructive: the memories reinforce each other, revealing a shared
      deep structure (synthesis is richer than either alone)
    - destructive: the memories tension each other, revealing a genuine
      contradiction or complementary perspective
    - neutral: the memories are largely orthogonal — different domains with
      little overlap
    """
    type: str  # "constructive" | "destructive" | "neutral"
    amplification: float  # > 1 constructive, < 1 destructive, ≈ 1 neutral
    synthesis: str  # natural-language description of the interference

    def __repr__(self) -> str:
        return (
            f"InterferencePattern(type={self.type!r}, "
            f"amplification={self.amplification:.3f}, "
            f"synthesis={self.synthesis[:80]!r}…)"
        )


# ─────────────────────────────────────────────
# Core engine
# ─────────────────────────────────────────────

class HolographicMemory:
    """
    ホログラフィック記憶システム

    Stores memories as holograms: each encoded memory carries projections
    of itself into every other domain. Recall is not a lookup but a resonance
    activation — querying for one concept simultaneously activates its
    cross-domain echoes.

    Architecture
    ────────────
    Memory storage:   list of MemoryHologram, indexed by domain
    Retrieval:        cosine-like token overlap between query and all memories
    Interference:     pairwise echo alignment score
    Boundary:         holographic summary encoding the whole collection
    Persistence:      JSON at data/akashic_memory.json

    Usage::

        mem = HolographicMemory()
        h = mem.encode("recursion is when a function calls itself", "code")
        results = mem.recall("self-reference in programs", domains=["code", "mathematics"])
        pattern = mem.find_interference(results[0], results[1])
        boundary = mem.get_boundary_encoding(results)
    """

    def __init__(
        self,
        storage_path: str = _DEFAULT_MEMORY_PATH,
        llm_fn: Callable[[str], str] | None = None,
    ) -> None:
        self._path = os.path.abspath(storage_path)
        self._llm_fn = llm_fn
        self._memories: list[MemoryHologram] = []
        self._load()

    # ── Public API ──────────────────────────────────────────────────────

    def encode(
        self,
        content: str,
        domain: str,
        context: dict | None = None,
    ) -> MemoryHologram:
        """
        Encode a new memory as a hologram with cross-domain projections.

        The encoding process:
        1. Project the content into all other domains using template echoes
           (and LLM if available)
        2. Compute the memory's interference score against the existing field
        3. Estimate Φ from cross-domain activation density
        4. Persist the new hologram

        Parameters
        ──────────
        content:  The raw content to remember
        domain:   The primary domain of this memory (e.g. "code", "biology")
        context:  Optional metadata dict (tags, source, conversation_id, etc.)

        Returns the fully encoded MemoryHologram.
        """
        if domain not in _ALL_DOMAINS:
            domain = self._nearest_domain(domain)

        echoes = self._project_cross_domain(content, domain, context)
        phi = self._estimate_phi(echoes, content)
        interference = self._compute_field_interference(content, domain)

        hologram = MemoryHologram(
            content=content,
            domain=domain,
            cross_domain_echoes=echoes,
            phi=phi,
            interference_score=interference,
        )

        self._memories.append(hologram)
        self._save()
        return hologram

    def recall(
        self,
        query: str,
        domains: list[str] | None = None,
        top_k: int = 5,
    ) -> list[MemoryHologram]:
        """
        Retrieve memories that resonate with the query.

        Unlike a vector database lookup, recall here activates cross-domain
        associations: a query about "recursion" will surface not only code
        memories but biology, philosophy, and mathematics memories whose
        cross-domain echoes mention recursion.

        Parameters
        ──────────
        query:    Natural language query
        domains:  Restrict search to these domains (None = all domains)
        top_k:    Return at most this many results

        Returns memories sorted by resonance score, highest first.
        """
        if not self._memories:
            return []

        query_tokens = set(self._tokenize(query))
        candidates = self._memories

        if domains:
            # Include memories in target domains AND memories whose echoes
            # for target domains are relevant
            candidates = [
                m for m in self._memories
                if m.domain in domains
                or any(
                    d in domains and self._token_overlap(
                        query_tokens, set(self._tokenize(m.echo_for(d)))
                    ) > 0
                    for d in (domains or _ALL_DOMAINS)
                )
            ]

        scored: list[tuple[float, MemoryHologram]] = []
        for mem in candidates:
            score = self._resonance_score(query_tokens, mem, domains)
            if score > 0:
                scored.append((score, mem))

        scored.sort(key=lambda x: x[0], reverse=True)
        return [mem for _, mem in scored[:top_k]]

    def find_interference(
        self,
        memory_a: MemoryHologram,
        memory_b: MemoryHologram,
    ) -> InterferencePattern:
        """
        Find the interference pattern between two memories.

        Constructive interference: their cross-domain echoes align and amplify
        each other — they share a deep structure.

        Destructive interference: their echoes are in tension — they represent
        genuinely competing perspectives or complementary opposites.

        Neutral: they are largely orthogonal — different domains, different
        content, no significant overlap or tension.
        """
        alignment_scores: list[float] = []
        shared_domains = set(memory_a.cross_domain_echoes) & set(memory_b.cross_domain_echoes)

        for domain in shared_domains:
            echo_a = set(self._tokenize(memory_a.echo_for(domain)))
            echo_b = set(self._tokenize(memory_b.echo_for(domain)))
            overlap = self._token_overlap(echo_a, echo_b)
            alignment_scores.append(overlap)

        if not alignment_scores:
            return InterferencePattern(
                type="neutral",
                amplification=1.0,
                synthesis=(
                    f"'{memory_a.domain}' and '{memory_b.domain}' memories "
                    f"have no shared domain echoes — they are orthogonal holograms."
                ),
            )

        mean_alignment = sum(alignment_scores) / len(alignment_scores)

        # Constructive: high shared token overlap in echoes
        if mean_alignment >= 0.25:
            amplification = 1.0 + mean_alignment * 2.0
            synthesis = self._synthesize_constructive(memory_a, memory_b, mean_alignment)
            return InterferencePattern(
                type="constructive",
                amplification=amplification,
                synthesis=synthesis,
            )

        # Check for tension words suggesting destructive interference
        tension_pairs = [
            ("order", "chaos"), ("deterministic", "random"), ("local", "global"),
            ("simple", "complex"), ("reducible", "emergent"), ("finite", "infinite"),
            ("bottom-up", "top-down"), ("discrete", "continuous"),
        ]
        content_ab = (memory_a.content + " " + memory_b.content).lower()
        tension_count = sum(
            1 for a, b in tension_pairs
            if a in content_ab and b in content_ab
        )

        if tension_count >= 2 or mean_alignment < 0.05:
            amplification = max(0.2, 1.0 - (tension_count * 0.15))
            synthesis = self._synthesize_destructive(memory_a, memory_b, tension_count)
            return InterferencePattern(
                type="destructive",
                amplification=amplification,
                synthesis=synthesis,
            )

        # Default: neutral with slight constructive lean
        synthesis = (
            f"Memories in '{memory_a.domain}' and '{memory_b.domain}' show "
            f"weak resonance (alignment={mean_alignment:.2f}). "
            f"They neither strongly reinforce nor oppose each other — "
            f"they may be exploring adjacent but distinct regions of the semantic field."
        )
        return InterferencePattern(
            type="neutral",
            amplification=1.0 + mean_alignment * 0.5,
            synthesis=synthesis,
        )

    def get_boundary_encoding(self, memories: list[MemoryHologram]) -> str:
        """
        Encode the holographic boundary summary of a collection of memories.

        Holographic principle: the information of a volume is encoded on its
        boundary surface. Applied cognitively: the essential information of a
        set of memories can be encoded in a lower-dimensional boundary summary
        that preserves the relational structure.

        The boundary encoding:
        1. Extracts the dominant domains across the collection
        2. Identifies the most active cross-domain bridges
        3. Computes the collective Φ of the set
        4. Returns a compact but information-rich summary

        This boundary can be stored as a "memory of memories" — a higher-order
        hologram that represents the collection without containing all its detail.
        """
        if not memories:
            return "∅ — empty memory collection, boundary is undefined."

        # Domain frequency
        domain_counts: dict[str, int] = {}
        for m in memories:
            domain_counts[m.domain] = domain_counts.get(m.domain, 0) + 1

        dominant_domain = max(domain_counts, key=lambda d: domain_counts[d])
        domain_summary = ", ".join(
            f"{d}×{c}" for d, c in sorted(domain_counts.items(), key=lambda x: -x[1])
        )

        # Cross-domain echo inventory: which bridge domains appear most?
        echo_domain_counts: dict[str, int] = {}
        for m in memories:
            for echo_domain in m.cross_domain_echoes:
                echo_domain_counts[echo_domain] = (
                    echo_domain_counts.get(echo_domain, 0) + 1
                )
        top_bridges = sorted(
            echo_domain_counts.items(), key=lambda x: -x[1]
        )[:3]
        bridge_summary = ", ".join(f"{d}({c})" for d, c in top_bridges)

        # Collective Φ
        phi_values = [m.phi for m in memories if m.phi > 0]
        collective_phi = sum(phi_values) / len(phi_values) if phi_values else 0.0

        # Content fingerprint: first 30 tokens from each memory, deduplicated
        all_tokens: set[str] = set()
        for m in memories:
            all_tokens.update(self._tokenize(m.content)[:15])
        stopwords = {
            "the", "a", "an", "is", "are", "was", "were", "be", "been",
            "being", "have", "has", "had", "do", "does", "did", "will",
            "would", "could", "should", "may", "might", "must", "shall",
            "to", "of", "in", "for", "on", "with", "at", "by", "from",
            "and", "or", "but", "not", "this", "that", "it", "its",
        }
        content_tokens = sorted(all_tokens - stopwords)[:20]
        token_fingerprint = " ".join(content_tokens)

        boundary = (
            f"HOLOGRAPHIC BOUNDARY ENCODING\n"
            f"━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n"
            f"Memory count:      {len(memories)}\n"
            f"Domains:           {domain_summary}\n"
            f"Primary domain:    {dominant_domain}\n"
            f"Top echo bridges:  {bridge_summary}\n"
            f"Collective Φ:      {collective_phi:.4f}\n"
            f"Content tokens:    {token_fingerprint}\n"
            f"━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n"
            f"This boundary encodes the relational structure of {len(memories)} "
            f"memories. The dominant domain '{dominant_domain}' anchors the "
            f"collection; the bridges into {bridge_summary.split('(')[0] if bridge_summary else 'unknown'} "
            f"suggest the collection's cross-domain reach. "
            f"Collective Φ={collective_phi:.3f} measures how integrated the "
            f"information across this set is."
        )
        return boundary

    def all_memories(self, domain: str | None = None) -> list[MemoryHologram]:
        """Return all stored memories, optionally filtered by domain."""
        if domain is None:
            return list(self._memories)
        return [m for m in self._memories if m.domain == domain]

    def clear(self) -> None:
        """Clear all memories and delete the persisted file."""
        self._memories = []
        if os.path.exists(self._path):
            os.remove(self._path)

    # ── Persistence ─────────────────────────────────────────────────────

    def _save(self) -> None:
        os.makedirs(os.path.dirname(self._path), exist_ok=True)
        data = [m.to_dict() for m in self._memories]
        with open(self._path, "w", encoding="utf-8") as f:
            json.dump(data, f, ensure_ascii=False, indent=2)

    def _load(self) -> None:
        if not os.path.exists(self._path):
            self._memories = []
            return
        try:
            with open(self._path, "r", encoding="utf-8") as f:
                data = json.load(f)
            self._memories = [MemoryHologram.from_dict(d) for d in data]
        except (json.JSONDecodeError, KeyError, TypeError):
            # Corrupt or incompatible file — start fresh
            self._memories = []

    # ── Cross-domain projection ──────────────────────────────────────────

    def _project_cross_domain(
        self,
        content: str,
        primary_domain: str,
        context: dict | None,
    ) -> dict[str, str]:
        """
        Generate cross-domain echoes for a piece of content.

        Strategy (degrading gracefully without LLM):
        1. Use template echoes for the primary domain
        2. Augment with content-specific nuance via LLM if available
        3. Tag echoes with context metadata if provided
        """
        echoes: dict[str, str] = {}
        domain_templates = _DOMAIN_ECHO_TEMPLATES.get(primary_domain, {})

        for target_domain, template in domain_templates.items():
            if target_domain == primary_domain:
                continue

            if self._llm_fn is not None:
                echo = self._llm_echo(content, primary_domain, target_domain, template)
            else:
                # Template echo: concrete and useful even without LLM
                echo = template

            if context:
                tags = context.get("tags", [])
                if isinstance(tags, list) and tags:
                    echo += f" [context: {', '.join(str(t) for t in tags[:3])}]"

            echoes[target_domain] = echo

        # Ensure all domains have at least a minimal echo
        for domain in _ALL_DOMAINS:
            if domain != primary_domain and domain not in echoes:
                echoes[domain] = (
                    f"Indirect echo of {primary_domain} memory in {domain} domain — "
                    f"no direct template bridge available."
                )

        return echoes

    def _llm_echo(
        self,
        content: str,
        source_domain: str,
        target_domain: str,
        template: str,
    ) -> str:
        """
        Ask the LLM to generate a specific cross-domain echo.
        Falls back to template if LLM fails.
        """
        prompt = (
            f"A memory from the '{source_domain}' domain:\n"
            f"  \"{content[:300]}\"\n\n"
            f"In one sentence, describe the echo of this memory in the "
            f"'{target_domain}' domain. Be concrete and specific. "
            f"Template hint: {template}"
        )
        try:
            result = self._llm_fn(prompt)
            if result and len(result.strip()) > 10:
                return result.strip()
        except Exception:
            pass
        return template

    # ── Retrieval scoring ────────────────────────────────────────────────

    def _resonance_score(
        self,
        query_tokens: set[str],
        memory: MemoryHologram,
        domains: list[str] | None,
    ) -> float:
        """
        Compute how strongly a memory resonates with a query.

        Score components:
        - Direct content overlap (weight: 1.0)
        - Cross-domain echo overlap for target domains (weight: 0.5 each)
        - Phi boost: high-Φ memories are slightly preferred (weight: 0.1)
        - Recency decay: older memories score slightly less (weight: 0.05)
        """
        score = 0.0

        # Direct content match
        content_tokens = set(self._tokenize(memory.content))
        score += self._token_overlap(query_tokens, content_tokens) * 1.0

        # Cross-domain echo match
        target_domains = domains if domains else _ALL_DOMAINS
        for domain in target_domains:
            if domain != memory.domain:
                echo = memory.echo_for(domain)
                echo_tokens = set(self._tokenize(echo))
                score += self._token_overlap(query_tokens, echo_tokens) * 0.5

        # Phi boost
        score += memory.phi * 0.1

        # Recency decay: memories older than 30 days lose 10% score
        age_days = (time.time() - memory.timestamp) / 86400
        if age_days > 30:
            score *= max(0.5, 1.0 - (age_days - 30) / 365 * 0.5)

        return score

    # ── Interference synthesis ───────────────────────────────────────────

    def _synthesize_constructive(
        self,
        a: MemoryHologram,
        b: MemoryHologram,
        alignment: float,
    ) -> str:
        """Generate synthesis text for constructive interference."""
        if self._llm_fn is not None:
            prompt = (
                f"Two memories are constructively interfering (alignment={alignment:.2f}):\n"
                f"Memory A ({a.domain}): \"{a.content[:200]}\"\n"
                f"Memory B ({b.domain}): \"{b.content[:200]}\"\n\n"
                f"In 2 sentences, describe the deeper pattern they share — "
                f"what universal structure are they both instances of?"
            )
            try:
                result = self._llm_fn(prompt)
                if result and len(result.strip()) > 20:
                    return result.strip()
            except Exception:
                pass

        # Local synthesis
        return (
            f"Constructive interference between '{a.domain}' and '{b.domain}' "
            f"memories (echo alignment={alignment:.2f}). "
            f"These memories amplify each other — they are likely expressions "
            f"of the same underlying pattern in different substrates. "
            f"Retrieving one should prime recall of the other."
        )

    def _synthesize_destructive(
        self,
        a: MemoryHologram,
        b: MemoryHologram,
        tension_count: int,
    ) -> str:
        """Generate synthesis text for destructive interference."""
        return (
            f"Destructive interference between '{a.domain}' and '{b.domain}' "
            f"memories (tension_pairs={tension_count}). "
            f"These memories are in tension — they may represent complementary "
            f"opposites or genuinely competing claims. "
            f"Holding both simultaneously without collapsing to either is the "
            f"cognitive move required here (via negativa, koan, dialectic)."
        )

    # ── Field-level interference ─────────────────────────────────────────

    def _compute_field_interference(self, content: str, domain: str) -> float:
        """
        How much does a new memory interfere with the existing memory field?

        High score: the new memory has high token overlap with existing memories
        across multiple domains → it is highly integrated into the field.

        Low score: the new memory is novel and isolated.
        """
        if not self._memories:
            return 0.0

        new_tokens = set(self._tokenize(content))
        overlap_scores: list[float] = []

        for existing in self._memories[-50:]:  # only check recent memories for performance
            existing_tokens = set(self._tokenize(existing.content))
            overlap = self._token_overlap(new_tokens, existing_tokens)
            overlap_scores.append(overlap)

        if not overlap_scores:
            return 0.0

        mean_overlap = sum(overlap_scores) / len(overlap_scores)
        max_overlap = max(overlap_scores)
        # Weighted average favoring the max (one strong connection matters)
        return round(0.4 * mean_overlap + 0.6 * max_overlap, 4)

    # ── Phi estimation ───────────────────────────────────────────────────

    def _estimate_phi(self, echoes: dict[str, str], content: str) -> float:
        """
        Estimate Tononi's Φ for a memory from its cross-domain echo richness.

        More non-trivial echoes → higher Φ.
        Echo richness = fraction of echo text that goes beyond the template default.
        """
        if not echoes:
            return 0.0

        rich_count = 0
        total = len(echoes)

        content_tokens = set(self._tokenize(content))
        for echo in echoes.values():
            echo_tokens = set(self._tokenize(echo))
            # An echo is "rich" if it shares more than 2 tokens with the content
            # (i.e., it's genuinely tied to this specific memory, not just generic)
            shared = len(content_tokens & echo_tokens)
            if shared >= 2:
                rich_count += 1

        base_phi = rich_count / max(1, total)

        # Bonus for multi-word content (more complex → higher Φ potential)
        word_count = len(content.split())
        complexity_bonus = min(0.2, word_count / 200)

        return round(min(1.0, base_phi + complexity_bonus), 4)

    # ── Utilities ────────────────────────────────────────────────────────

    def _tokenize(self, text: str) -> list[str]:
        """Simple lowercase word tokenizer, strips punctuation."""
        return re.findall(r"[a-z]{3,}", text.lower())

    def _token_overlap(self, a: set[str], b: set[str]) -> float:
        """
        Jaccard-like overlap but using the smaller set as denominator.
        This makes it asymmetric: a short query can match a long memory fully.
        """
        if not a or not b:
            return 0.0
        intersection = len(a & b)
        denominator = min(len(a), len(b))
        return intersection / denominator

    def _nearest_domain(self, domain_hint: str) -> str:
        """
        Map an unknown domain string to the nearest known domain.
        Falls back to "philosophy" as the most general domain.
        """
        hint_lower = domain_hint.lower()
        domain_aliases = {
            "coding": "code",
            "programming": "code",
            "software": "code",
            "science": "physics",
            "maths": "mathematics",
            "math": "mathematics",
            "life": "biology",
            "living": "biology",
            "mind": "consciousness",
            "cognition": "consciousness",
            "data": "information",
            "universe": "cosmology",
            "space": "cosmology",
            "thought": "philosophy",
            "meaning": "philosophy",
            "beauty": "art_aesthetics",
            "design": "art_aesthetics",
            "music": "art_aesthetics",
        }
        if hint_lower in domain_aliases:
            return domain_aliases[hint_lower]
        for known in _ALL_DOMAINS:
            if hint_lower in known or known in hint_lower:
                return known
        return "philosophy"
